### ISSUE TITLE
As a developer, we can use a external CLI Interface to handle command line input from the user

### ISSUE THREAD

**Issue by Christorob** [ITU-BDSA23-GROUP13/Chirp#1]
This refactoring will allow greater ease of use and understanding for the developer.

Acceptance criteria:
- [x] The CLI interface is installed correctly, and works.
- [x] The new refactoring has the same or greater functionality.
- [x] All developers understand the new implementation post refactoring.

**Comment by Daniel9915** [comment]
We have decided to go with the CLI Interface, "System.CommandLine" made by Microsoft.
