### ISSUE TITLE
Make a web API so that cheeps can be stored on a server, so multiple users can read and store cheeps from a shared database.

### ISSUE THREAD

**Issue by copeitu** [ITU-BDSA23-GROUP13/Chirp#31]
Acceptance Criteria:
- [x] Make endpoint for reading cheeps "/cheeps"
- [x] Make endpoint for storing cheep "/cheep" with cheep stored sent as JSON data.
- [x] Works locally with localhost.

**Comment by marc9622** [comment]
Updated the issue text
