### ISSUE TITLE
As a team of developers, it would be beneficial to ustilise "proper" pair programming

### ISSUE THREAD

**Issue by copeitu** [ITU-BDSA23-GROUP13/Chirp#43]
Acceptance criteria:

We are acustomed to using the method.

From now on, try to be conscious about how you do pair programming. As described in the lecture, switch roles of driver and navigator every 15/20 minutes. Commits are done now always by the group member that is currently the driver with correctly attributed co-author.

**Comment by copeitu** [comment]
How do we go along with this? I think we need to switch coding partners often - what do you think and do you have some great ideas on how to do that?

**Comment by Christorob** [comment]
I think that when starting a new project, for example starting work on a new issue, we can decide on a pair who will work on it. When that issue is solved, we can try different pairings.
